# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f9541fe7d10fa4753c746be85fbaec70e1d38bf10e7b4804406c07da150a3de8c9419dd1019ce7d6c96c80723323485bca491aa177f84c185cb1f6aaf7ffbfc6

test:
  secret_key_base: 447b6674fba7e681abb09f2dc446e0e0f8ed8afebb66da250822585b8dfafbfcf9929eb4e7e3c39d1b7bd3dca810ad288fb78c13ecf442a1cefaa7a6c99523d2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
